<?php
    /** @var \Magento\Framework\Escaper $escaper */
    $element = $this->getElement();
?>
<div id="<?= $element->getHtmlId();?>" class="dragula-element <?= $element->getData('disabled') ? 'disabled' : '' ;?>">
    <div data-type="container" data-name="available">
    <?php foreach ($block->getAvailableOptions() as $option): ?>
        <div data-type="block" data-name="<?= $escaper->escapeHtmlAttr($option['value']) ?>" class="header-config">
            <span class="name"><?= $escaper->escapeHtml($option['label']) ?></span>
        </div>
    <?php endforeach; ?>
    </div>
</div>
