<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Swissup\ThemeEditorArgentoLuxury\Block\Html\Header\LogoAlt $block */
?>

<?php
    $logoWidth = $block->getLogoWidth();
    $logoHeight = $block->getLogoHeight();
    $logoBlock = $this->getLayout()->getBlock('logo');
    if ($logoBlock) {
        $logoWidth = $logoBlock->getLogoWidth();
        $logoHeight = $logoBlock->getLogoHeight();
    }
?>

<?php if ($block->getLogoSrc()):?>
    <img src="<?= $escaper->escapeUrl($block->getLogoSrc()) ?>"
         alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
         class="logo-alt"
         <?= /* @noEscape */ $logoWidth ? 'width="' . $logoWidth . '"' : '' ?>
         <?= /* @noEscape */ $logoHeight ? 'height="' . $logoHeight . '"' : '' ?>
    />
<?php endif; ?>
